# Generated by Django 3.2.5 on 2021-08-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('generation', models.CharField(blank=True, max_length=8)),
                ('price', models.CharField(max_length=7)),
                ('mainimage', models.ImageField(upload_to='images')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
