# Generated by Django 3.2.5 on 2021-08-11 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('TESLA', 'TESLA'), ('SUZUKI', 'SUZUKI')], max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('year_production', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.car')),
            ],
        ),
    ]
